# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-unit-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Checkout configs to branch add-migration-files-table
      run: cd configs && git checkout -b add-migration-files-table && cd ..

    - name: Deploy server-core artefact
      run: cd .. && git clone https://github.com/OpenSRP/opensrp-server-core.git && cd opensrp-server-core && git checkout implement-client-migration-file-models-repositories && mvn clean install -Dmaven.test.skip=true -Dmaven.javadoc.skip=true && cd ../opensrp-server-web

    - name: Run Unit tests with Maven
      run: mvn -B clean test jacoco:report --file pom.xml --no-transfer-progress
    - name: Set Branch name Environment variable 
      env:
        BRANCH_NAME_OR_REF: ${{ github.head_ref || github.ref }}
      run: echo "BRANCH_NAME=${BRANCH_NAME_OR_REF#refs/heads/}" >> $GITHUB_ENV
    - name: Set PR Number Environment variable 
      run: |
        echo "PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")" >> $GITHUB_ENV
    - name: Upload coveralls report
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
      run: |
         mvn -B coveralls:report --file pom.xml \
          --no-transfer-progress \
          -D repoToken="$COVERALLS_REPO_TOKEN" \
          -D serviceName=Github \
          -D branch="$BRANCH_NAME" \
          -D pullRequest="$PR_NUMBER" \
